[package]
name = "cubacadabra-engine"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mlua = { version = "0.12.1", default-features = false, features = ["luau", "vendored"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
